/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    products: Product;
    categories: Category;
    orders: Order;
    customers: Customer;
    media: Media;
    'contact-messages': ContactMessage;
    posts: Post;
    'shipping-methods': ShippingMethod;
    'product-templates': ProductTemplate;
    designs: Design;
    'production-jobs': ProductionJob;
    shipments: Shipment;
    'tracking-events': TrackingEvent;
    locations: Location;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'shipping-methods': ShippingMethodsSelect<false> | ShippingMethodsSelect<true>;
    'product-templates': ProductTemplatesSelect<false> | ProductTemplatesSelect<true>;
    designs: DesignsSelect<false> | DesignsSelect<true>;
    'production-jobs': ProductionJobsSelect<false> | ProductionJobsSelect<true>;
    shipments: ShipmentsSelect<false> | ShipmentsSelect<true>;
    'tracking-events': TrackingEventsSelect<false> | TrackingEventsSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    header: Header;
    footer: Footer;
    'seo-settings': SeoSetting;
    'payment-settings': PaymentSetting;
    'shipping-settings': ShippingSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'seo-settings': SeoSettingsSelect<false> | SeoSettingsSelect<true>;
    'payment-settings': PaymentSettingsSelect<false> | PaymentSettingsSelect<true>;
    'shipping-settings': ShippingSettingsSelect<false> | ShippingSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'manager' | 'editor' | 'customer';
  status: 'active' | 'inactive';
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  /**
   * URL-friendly version of the name
   */
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  price: number;
  compareAtPrice?: number | null;
  /**
   * Extra charge applied per unit when the customer customizes this product. Added on top of the base price.
   */
  additionalCustomizationPrice?: number | null;
  sku?: string | null;
  barcode?: string | null;
  images?:
    | {
        image: number | Media;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  category: number | Category;
  inventory?: {
    quantity?: number | null;
    lowStockThreshold?: number | null;
    trackInventory?: boolean | null;
  };
  status: 'active' | 'inactive' | 'draft' | 'outOfStock';
  featured?: boolean | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  weight?: number | null;
  dimensions?: {
    length?: number | null;
    width?: number | null;
    height?: number | null;
  };
  specifications?:
    | {
        name: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * When enabled, customers can personalize this product with text, images, or a full design before adding to cart.
   */
  isCustomizable?: boolean | null;
  /**
   * Design templates available for this product. Shown in the customer designer for quick-start customization.
   */
  templates?: (number | ProductTemplate)[] | null;
  /**
   * Configure how customers can personalize this product.
   */
  customization?: {
    generalSettings: {
      /**
       * What kind of customization the customer can perform on this product.
       */
      customizationType: 'text' | 'image' | 'image_text' | 'full_designer';
    };
    productionSettings?: {
      /**
       * Estimated additional production days for customized orders.
       */
      productionTime?: number | null;
      /**
       * If enabled, the customer receives a proof for approval before production begins.
       */
      designApprovalRequired?: boolean | null;
      /**
       * Which facility or partner handles production of this customizable product.
       */
      printProvider?: ('in_house' | 'partner_a' | 'partner_b' | 'partner_c') | null;
    };
    printSpecifications: {
      /**
       * Width of the area available for printing.
       */
      printableAreaWidth: number;
      /**
       * Height of the area available for printing.
       */
      printableAreaHeight: number;
      printableAreaUnit: 'mm' | 'cm' | 'in' | 'px';
      /**
       * Minimum recommended resolution for uploaded images. 300 DPI is standard for print.
       */
      minimumImageResolution?: number | null;
      /**
       * Extra margin beyond the trim line (in the selected unit). Standard is 3 mm.
       */
      bleedArea?: number | null;
      /**
       * Margin inside the trim line where critical content should stay. Standard is 5 mm.
       */
      safeArea?: number | null;
    };
    uploadRules?: {
      /**
       * Maximum file size for customer-uploaded designs.
       */
      maximumUploadSize?: number | null;
      allowedImageFormats?: ('png' | 'jpg' | 'jpeg' | 'svg' | 'pdf' | 'ai' | 'psd' | 'tiff')[] | null;
      /**
       * If enabled, customers can upload PNGs with transparent backgrounds.
       */
      allowTransparentPNG?: boolean | null;
    };
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    /**
     * Comma-separated keywords
     */
    keywords?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * URL-friendly version of the name (auto-generated from name)
   */
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  /**
   * Optional parent category for hierarchical structure
   */
  parent?: (number | null) | Category;
  featured?: boolean | null;
  status: 'active' | 'inactive';
  /**
   * Lower numbers appear first
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-templates".
 */
export interface ProductTemplate {
  id: number;
  /**
   * A descriptive name for this template (e.g. 'Birthday Mug Design').
   */
  title: string;
  /**
   * URL-safe identifier. Auto-generated from title if left empty.
   */
  slug: string;
  /**
   * Internal notes about this template — its purpose, style, or usage.
   */
  description?: string | null;
  status: 'draft' | 'published' | 'archived';
  /**
   * Full-resolution preview shown in the template detail view and gallery.
   */
  previewImage?: (number | null) | Media;
  /**
   * Small thumbnail shown in list views and template pickers (recommended: 200x200).
   */
  thumbnail?: (number | null) | Media;
  /**
   * The product this template is designed for (e.g. a coffee mug, t-shirt, banner).
   */
  linkedProduct: number | Product;
  /**
   * Optional theme or occasion category (e.g. Birthday, Corporate, Wedding).
   */
  category?: (number | null) | Category;
  /**
   * The admin user who created this template.
   */
  createdBy?: (number | null) | User;
  /**
   * The admin user who last modified this template.
   */
  updatedBy?: (number | null) | User;
  /**
   * The overall design canvas dimensions. This is the full working area.
   */
  canvas: {
    width: number;
    height: number;
    unit: 'px' | 'mm' | 'cm' | 'in';
    /**
     * Dots per inch. Determines the print resolution. 300 DPI is standard for print.
     */
    dpi?: number | null;
  };
  /**
   * Defines the printable region, bleed, and safe margins within the canvas.
   */
  printAreas: {
    printableArea: {
      x?: number | null;
      y?: number | null;
      width: number;
      height: number;
    };
    /**
     * Extra margin beyond the trim line for full-bleed designs. Standard is 3 mm.
     */
    bleedArea?: number | null;
    /**
     * Margin inside the trim line where text and critical content should stay.
     */
    safeArea?: number | null;
  };
  /**
   * The serialized design data. This JSON describes the template layers and their properties.
   */
  templateData?: {
    /**
     * Semantic version for this template (e.g. 1.0.0, 2.1.0).
     */
    templateVersion?: string | null;
    /**
     * The raw template data in JSON format. Contains layers, text objects, image placeholders, fonts, colors, and positions.
     */
    templateJSON?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    layerCount?: number | null;
    /**
     * Number of layers the customer is allowed to edit (excluding locked/locked backgrounds).
     */
    editableLayerCount?: number | null;
  };
  /**
   * Previous versions of the template data. New entries are pushed automatically on save.
   */
  versionHistory?:
    | {
        version: string;
        templateJSON:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        changedBy?: (number | null) | User;
        changeNote?: string | null;
        changedAt: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Keywords for searchability (e.g. birthday, corporate, wedding).
   */
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Controls display order. Lower numbers appear first.
   */
  sortOrder?: number | null;
  /**
   * If checked, this template is the default starting point for its linked product.
   */
  isDefault?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * Unique order identifier (e.g., ORD-000001)
   */
  orderNumber: string;
  customer: number | Customer;
  items: {
    product: number | Product;
    name: string;
    sku?: string | null;
    quantity: number;
    price: number;
    total: number;
    /**
     * Captured only for customized products. Persists the full design package onto the order for the print workflow.
     */
    design?: {
      designId?: (number | null) | Design;
      templateId?: string | null;
      templateVersion?: string | null;
      designJSON?:
        | {
            [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
      options?:
        | {
            [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
      previewImage?: (number | null) | Media;
      assets?:
        | {
            asset: number | Media;
            id?: string | null;
          }[]
        | null;
      productionMetadata?:
        | {
            [k: string]: unknown;
          }
        | unknown[]
        | string
        | number
        | boolean
        | null;
    };
    id?: string | null;
  }[];
  subtotal: number;
  tax?: number | null;
  shipping?: number | null;
  shippingMethod?: {
    id?: string | null;
    name?: string | null;
    zone?: string | null;
  };
  total: number;
  status: 'pending' | 'confirmed' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'refunded';
  paymentStatus: 'pending' | 'paid' | 'failed' | 'refunded';
  paymentMethod?: string | null;
  shippingAddress: {
    fullName: string;
    address: string;
    city: string;
    state: string;
    postalCode?: string | null;
    country: string;
    phone: string;
  };
  notes?: string | null;
  trackingNumber?: string | null;
  trackingUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  phone?: string | null;
  addresses?:
    | {
        label?: string | null;
        fullName: string;
        address: string;
        city: string;
        state: string;
        postalCode?: string | null;
        country: string;
        phone: string;
        isDefault?: boolean | null;
        id?: string | null;
      }[]
    | null;
  totalOrders?: number | null;
  totalSpent?: number | null;
  /**
   * Internal notes about this customer
   */
  notes?: string | null;
  status: 'active' | 'inactive' | 'blocked';
  updatedAt: string;
  createdAt: string;
}
/**
 * Persisted customer designs. Each document is a complete customization package that can be attached to a cart line or an order item.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "designs".
 */
export interface Design {
  id: number;
  product: number | Product;
  /**
   * Template this design was built from.
   */
  template?: (number | null) | ProductTemplate;
  templateVersion?: string | null;
  /**
   * The complete filled-in design (layers, text, images, geometry).
   */
  designJSON:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Customer answers keyed by placeholder id (text + image refs).
   */
  options?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Optimized preview thumbnail used in cart and checkout.
   */
  previewImage?: (number | null) | Media;
  /**
   * Media assets uploaded by the customer, linked to this design.
   */
  assets?:
    | {
        asset: number | Media;
        /**
         * The image placeholder this asset fills.
         */
        placeholderId?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Print-ready metadata consumed by the print workflow.
   */
  productionMetadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Authenticated user this design belongs to (if any).
   */
  owner?: (number | null) | User;
  /**
   * Anonymous session token for guests so they can restore unfinished designs.
   */
  guestToken?: string | null;
  /**
   * Lifecycle: draft (in progress), saved (in cart), ordered (checkout complete).
   */
  status: 'draft' | 'saved' | 'ordered';
  /**
   * Set when the design is attached to a completed order.
   */
  orderNumber?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  subject: string;
  message: string;
  status: 'new' | 'in-progress' | 'resolved' | 'closed';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * URL-friendly version of the title (auto-generated if left blank)
   */
  slug: string;
  /**
   * A short summary shown on cards and search results.
   */
  excerpt?: string | null;
  /**
   * The full article body. Use headings for the table of contents.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Large banner image used at the top of the article and on cards.
   */
  heroImage?: (number | null) | Media;
  /**
   * Optional additional images displayed within the article.
   */
  gallery?:
    | {
        image: number | Media;
        alt?: string | null;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  category?: (number | null) | Category;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  author: {
    name: string;
    role?: string | null;
    avatar?: (number | null) | Media;
    bio?: string | null;
  };
  /**
   * When the article was published.
   */
  publishDate: string;
  /**
   * Featured articles appear in the hero carousel on the news page.
   */
  featured?: boolean | null;
  status: 'draft' | 'published';
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    /**
     * Comma-separated keywords
     */
    keywords?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-methods".
 */
export interface ShippingMethod {
  id: number;
  name: string;
  description?: string | null;
  baseFee: number;
  estimatedDelivery?: string | null;
  isActive?: boolean | null;
  /**
   * Set different fees for specific zones. Leave empty to use the base fee for all zones.
   */
  zoneFees?:
    | {
        zone: 'london' | 'amsterdam' | 'manchester' | 'other-states';
        fee: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Print production jobs auto-created from customized orders after payment is confirmed.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "production-jobs".
 */
export interface ProductionJob {
  id: number;
  /**
   * Human-readable reference (e.g. PRD-XXXX).
   */
  jobNumber: string;
  /**
   * The order this production job fulfils.
   */
  order: number | Order;
  /**
   * Current step in the production workflow.
   */
  status:
    | 'pending_review'
    | 'approved'
    | 'printing'
    | 'quality_check'
    | 'packaging'
    | 'ready_for_shipment'
    | 'shipped'
    | 'delivered'
    | 'rejected';
  provider: 'in_house' | 'printful' | 'printify' | 'gelato' | 'custom';
  /**
   * Provider-side job/order id once dispatched externally.
   */
  externalId?: string | null;
  /**
   * Raw status string reported by the provider.
   */
  externalStatus?: string | null;
  /**
   * When the job was dispatched to the provider.
   */
  submittedAt?: string | null;
  /**
   * Production sign-off before printing begins.
   */
  review?: {
    status?: ('pending' | 'approved' | 'rejected') | null;
    reviewedBy?: (number | null) | User;
    reviewedAt?: string | null;
    /**
     * Production review notes for the artwork.
     */
    comments?: string | null;
    /**
     * Internal approval note (optional).
     */
    approvalNote?: string | null;
  };
  itemCount?: number | null;
  /**
   * Each customized line isolated one per product/print area.
   */
  items?:
    | {
        product?: (number | null) | Product;
        name?: string | null;
        sku?: string | null;
        quantity?: number | null;
        unitPrice?: number | null;
        /**
         * Where on the product this design is printed.
         */
        printAreas?: ('front' | 'back' | 'inside' | 'wrap' | 'left' | 'right' | 'top' | 'bottom')[] | null;
        templateVersion?: string | null;
        /**
         * Full serialized customer design (source of truth).
         */
        designJSON?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        /**
         * Customer text/image answers keyed by placeholder id.
         */
        options?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        production?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        previewImage?: (number | null) | Media;
        assets?:
          | {
              asset: number | Media;
              placeholderId?: string | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Generated SVG/PNG/PDF masters.
         */
        printReadyFiles?:
          | {
              format?: string | null;
              widthPx?: number | null;
              heightPx?: number | null;
              unit?: string | null;
              dpi?: number | null;
              file?: (number | null) | Media;
              name?: string | null;
              /**
               * Byte size.
               */
              size?: number | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Audit trail of status changes and staff actions.
   */
  history?:
    | {
        status?: string | null;
        action: string;
        note?: string | null;
        actor?: (number | null) | User;
        at?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Internal comms across shifts.
   */
  staffNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipments".
 */
export interface Shipment {
  id: number;
  /**
   * Auto-generated, human-readable identifier (e.g. SC-2026-000001).
   */
  trackingNumber: string;
  /**
   * Account holder this shipment belongs to, when applicable.
   */
  customer?: (number | null) | Customer;
  sender: {
    name: string;
    company?: string | null;
    phone: string;
    email?: string | null;
  };
  recipient: {
    name: string;
    company?: string | null;
    phone: string;
    email?: string | null;
  };
  origin: number | Location;
  destination: number | Location;
  /**
   * Latest known location. Kept in sync with tracking events.
   */
  currentLocation?: (number | null) | Location;
  status:
    | 'created'
    | 'pickup-scheduled'
    | 'picked-up'
    | 'in-transit'
    | 'out-for-delivery'
    | 'delivered'
    | 'delayed'
    | 'exception'
    | 'cancelled'
    | 'returned';
  /**
   * The delivery service/method assigned to this shipment.
   */
  deliveryService?: (number | null) | ShippingMethod;
  estimatedDelivery?: string | null;
  package?: {
    description?: string | null;
    content?: string | null;
    quantity?: number | null;
    weight?: number | null;
    weightUnit?: ('kg' | 'lb') | null;
    length?: number | null;
    width?: number | null;
    height?: number | null;
    declaredValue?: number | null;
    /**
     * Sender's own reference for this package.
     */
    referenceNumber?: string | null;
    isFragile?: boolean | null;
  };
  /**
   * Historical journey. Events are created automatically from status changes.
   */
  trackingEvents?: (number | TrackingEvent)[] | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Hubs, depots, and pickup points across the delivery network.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  name: string;
  type: 'hub' | 'sorting-facility' | 'depot' | 'pickup-point' | 'partner-point';
  address?: string | null;
  city?: string | null;
  country?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Historical journey milestones for shipments. Created automatically from status changes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tracking-events".
 */
export interface TrackingEvent {
  id: number;
  shipment: number | Shipment;
  status:
    | 'created'
    | 'pickup-scheduled'
    | 'picked-up'
    | 'in-transit'
    | 'out-for-delivery'
    | 'delivered'
    | 'delayed'
    | 'exception'
    | 'cancelled'
    | 'returned';
  dateTime: string;
  location?: (number | null) | Location;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: number | ContactMessage;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'shipping-methods';
        value: number | ShippingMethod;
      } | null)
    | ({
        relationTo: 'product-templates';
        value: number | ProductTemplate;
      } | null)
    | ({
        relationTo: 'designs';
        value: number | Design;
      } | null)
    | ({
        relationTo: 'production-jobs';
        value: number | ProductionJob;
      } | null)
    | ({
        relationTo: 'shipments';
        value: number | Shipment;
      } | null)
    | ({
        relationTo: 'tracking-events';
        value: number | TrackingEvent;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  price?: T;
  compareAtPrice?: T;
  additionalCustomizationPrice?: T;
  sku?: T;
  barcode?: T;
  images?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  category?: T;
  inventory?:
    | T
    | {
        quantity?: T;
        lowStockThreshold?: T;
        trackInventory?: T;
      };
  status?: T;
  featured?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  weight?: T;
  dimensions?:
    | T
    | {
        length?: T;
        width?: T;
        height?: T;
      };
  specifications?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  isCustomizable?: T;
  templates?: T;
  customization?:
    | T
    | {
        generalSettings?:
          | T
          | {
              customizationType?: T;
            };
        productionSettings?:
          | T
          | {
              productionTime?: T;
              designApprovalRequired?: T;
              printProvider?: T;
            };
        printSpecifications?:
          | T
          | {
              printableAreaWidth?: T;
              printableAreaHeight?: T;
              printableAreaUnit?: T;
              minimumImageResolution?: T;
              bleedArea?: T;
              safeArea?: T;
            };
        uploadRules?:
          | T
          | {
              maximumUploadSize?: T;
              allowedImageFormats?: T;
              allowTransparentPNG?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  image?: T;
  parent?: T;
  featured?: T;
  status?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  customer?: T;
  items?:
    | T
    | {
        product?: T;
        name?: T;
        sku?: T;
        quantity?: T;
        price?: T;
        total?: T;
        design?:
          | T
          | {
              designId?: T;
              templateId?: T;
              templateVersion?: T;
              designJSON?: T;
              options?: T;
              previewImage?: T;
              assets?:
                | T
                | {
                    asset?: T;
                    id?: T;
                  };
              productionMetadata?: T;
            };
        id?: T;
      };
  subtotal?: T;
  tax?: T;
  shipping?: T;
  shippingMethod?:
    | T
    | {
        id?: T;
        name?: T;
        zone?: T;
      };
  total?: T;
  status?: T;
  paymentStatus?: T;
  paymentMethod?: T;
  shippingAddress?:
    | T
    | {
        fullName?: T;
        address?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  notes?: T;
  trackingNumber?: T;
  trackingUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  addresses?:
    | T
    | {
        label?: T;
        fullName?: T;
        address?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
        isDefault?: T;
        id?: T;
      };
  totalOrders?: T;
  totalSpent?: T;
  notes?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  subject?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  heroImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        alt?: T;
        caption?: T;
        id?: T;
      };
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  author?:
    | T
    | {
        name?: T;
        role?: T;
        avatar?: T;
        bio?: T;
      };
  publishDate?: T;
  featured?: T;
  status?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-methods_select".
 */
export interface ShippingMethodsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  baseFee?: T;
  estimatedDelivery?: T;
  isActive?: T;
  zoneFees?:
    | T
    | {
        zone?: T;
        fee?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-templates_select".
 */
export interface ProductTemplatesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  status?: T;
  previewImage?: T;
  thumbnail?: T;
  linkedProduct?: T;
  category?: T;
  createdBy?: T;
  updatedBy?: T;
  canvas?:
    | T
    | {
        width?: T;
        height?: T;
        unit?: T;
        dpi?: T;
      };
  printAreas?:
    | T
    | {
        printableArea?:
          | T
          | {
              x?: T;
              y?: T;
              width?: T;
              height?: T;
            };
        bleedArea?: T;
        safeArea?: T;
      };
  templateData?:
    | T
    | {
        templateVersion?: T;
        templateJSON?: T;
        layerCount?: T;
        editableLayerCount?: T;
      };
  versionHistory?:
    | T
    | {
        version?: T;
        templateJSON?: T;
        changedBy?: T;
        changeNote?: T;
        changedAt?: T;
        id?: T;
      };
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  sortOrder?: T;
  isDefault?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "designs_select".
 */
export interface DesignsSelect<T extends boolean = true> {
  product?: T;
  template?: T;
  templateVersion?: T;
  designJSON?: T;
  options?: T;
  previewImage?: T;
  assets?:
    | T
    | {
        asset?: T;
        placeholderId?: T;
        id?: T;
      };
  productionMetadata?: T;
  owner?: T;
  guestToken?: T;
  status?: T;
  orderNumber?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "production-jobs_select".
 */
export interface ProductionJobsSelect<T extends boolean = true> {
  jobNumber?: T;
  order?: T;
  status?: T;
  provider?: T;
  externalId?: T;
  externalStatus?: T;
  submittedAt?: T;
  review?:
    | T
    | {
        status?: T;
        reviewedBy?: T;
        reviewedAt?: T;
        comments?: T;
        approvalNote?: T;
      };
  itemCount?: T;
  items?:
    | T
    | {
        product?: T;
        name?: T;
        sku?: T;
        quantity?: T;
        unitPrice?: T;
        printAreas?: T;
        templateVersion?: T;
        designJSON?: T;
        options?: T;
        production?: T;
        previewImage?: T;
        assets?:
          | T
          | {
              asset?: T;
              placeholderId?: T;
              id?: T;
            };
        printReadyFiles?:
          | T
          | {
              format?: T;
              widthPx?: T;
              heightPx?: T;
              unit?: T;
              dpi?: T;
              file?: T;
              name?: T;
              size?: T;
              id?: T;
            };
        id?: T;
      };
  history?:
    | T
    | {
        status?: T;
        action?: T;
        note?: T;
        actor?: T;
        at?: T;
        id?: T;
      };
  staffNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipments_select".
 */
export interface ShipmentsSelect<T extends boolean = true> {
  trackingNumber?: T;
  customer?: T;
  sender?:
    | T
    | {
        name?: T;
        company?: T;
        phone?: T;
        email?: T;
      };
  recipient?:
    | T
    | {
        name?: T;
        company?: T;
        phone?: T;
        email?: T;
      };
  origin?: T;
  destination?: T;
  currentLocation?: T;
  status?: T;
  deliveryService?: T;
  estimatedDelivery?: T;
  package?:
    | T
    | {
        description?: T;
        content?: T;
        quantity?: T;
        weight?: T;
        weightUnit?: T;
        length?: T;
        width?: T;
        height?: T;
        declaredValue?: T;
        referenceNumber?: T;
        isFragile?: T;
      };
  trackingEvents?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tracking-events_select".
 */
export interface TrackingEventsSelect<T extends boolean = true> {
  shipment?: T;
  status?: T;
  dateTime?: T;
  location?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  address?: T;
  city?: T;
  country?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  siteDescription?: string | null;
  logo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  contactEmail?: string | null;
  contactPhone?: string | null;
  address?: {
    street?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  socialLinks?: {
    facebook?: string | null;
    instagram?: string | null;
    twitter?: string | null;
    linkedin?: string | null;
  };
  currency?: ('EUR' | 'GBP') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems: {
    label: string;
    /**
     * Use / for root, e.g., /products, /about
     */
    link: string;
    type?: ('link' | 'dropdown') | null;
    children?:
      | {
          label: string;
          link: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Show this item as highlighted/CTA
     */
    highlighted?: boolean | null;
    id?: string | null;
  }[];
  announcementBar?: {
    enabled?: boolean | null;
    text?: string | null;
    link?: string | null;
    linkLabel?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  description?: string | null;
  columns?:
    | {
        title: string;
        links: {
          label: string;
          link: string;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  bottomLinks?:
    | {
        label: string;
        link: string;
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-settings".
 */
export interface SeoSetting {
  id: number;
  defaultTitle?: string | null;
  /**
   * Use %s for the page title. Example: %s | AquaBest Brands
   */
  titleTemplate?: string | null;
  defaultDescription?: string | null;
  /**
   * Comma-separated keywords
   */
  defaultKeywords?: string | null;
  /**
   * Default image for social media sharing (1200x630px recommended)
   */
  ogImage?: (number | null) | Media;
  twitterHandle?: string | null;
  googleSiteVerification?: string | null;
  /**
   * e.g., G-XXXXXXXXXX or UA-XXXXXXXXX-X
   */
  googleAnalyticsId?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-settings".
 */
export interface PaymentSetting {
  id: number;
  cod?: {
    enabled?: boolean | null;
    label?: string | null;
    description?: string | null;
  };
  paystack?: {
    paystackEnabled?: boolean | null;
    paystackSecretKey?: string | null;
  };
  stripe?: {
    stripeEnabled?: boolean | null;
    stripeSecretKey?: string | null;
  };
  flutterwave?: {
    flutterwaveEnabled?: boolean | null;
    flutterwaveSecretKey?: string | null;
  };
  bankTransfer?: {
    enabled?: boolean | null;
    label?: string | null;
    description?: string | null;
    accountName?: string | null;
    accountNumber?: string | null;
    bankName?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-settings".
 */
export interface ShippingSetting {
  id: number;
  /**
   * Orders with subtotal above this amount qualify for free shipping.
   */
  freeShippingThreshold?: number | null;
  /**
   * Define delivery zones. The customer's city/state is matched against these.
   */
  zones?:
    | {
        name: string;
        /**
         * Used internally to match customer location. Use lowercase, e.g. 'amsterdam', 'london'.
         */
        key: string;
        /**
         * Comma-separated list of cities in this zone.
         */
        cities?: string | null;
        /**
         * Comma-separated list of states covered by this zone.
         */
        states?: string | null;
        isActive?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  logo?: T;
  favicon?: T;
  contactEmail?: T;
  contactPhone?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
      };
  socialLinks?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        twitter?: T;
        linkedin?: T;
      };
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        link?: T;
        type?: T;
        children?:
          | T
          | {
              label?: T;
              link?: T;
              id?: T;
            };
        highlighted?: T;
        id?: T;
      };
  announcementBar?:
    | T
    | {
        enabled?: T;
        text?: T;
        link?: T;
        linkLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  description?: T;
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              link?: T;
              id?: T;
            };
        id?: T;
      };
  bottomLinks?:
    | T
    | {
        label?: T;
        link?: T;
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-settings_select".
 */
export interface SeoSettingsSelect<T extends boolean = true> {
  defaultTitle?: T;
  titleTemplate?: T;
  defaultDescription?: T;
  defaultKeywords?: T;
  ogImage?: T;
  twitterHandle?: T;
  googleSiteVerification?: T;
  googleAnalyticsId?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-settings_select".
 */
export interface PaymentSettingsSelect<T extends boolean = true> {
  cod?:
    | T
    | {
        enabled?: T;
        label?: T;
        description?: T;
      };
  paystack?:
    | T
    | {
        paystackEnabled?: T;
        paystackSecretKey?: T;
      };
  stripe?:
    | T
    | {
        stripeEnabled?: T;
        stripeSecretKey?: T;
      };
  flutterwave?:
    | T
    | {
        flutterwaveEnabled?: T;
        flutterwaveSecretKey?: T;
      };
  bankTransfer?:
    | T
    | {
        enabled?: T;
        label?: T;
        description?: T;
        accountName?: T;
        accountNumber?: T;
        bankName?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-settings_select".
 */
export interface ShippingSettingsSelect<T extends boolean = true> {
  freeShippingThreshold?: T;
  zones?:
    | T
    | {
        name?: T;
        key?: T;
        cities?: T;
        states?: T;
        isActive?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}